from typing import List, Dict, Any, Optional
from .synthesia_generator import SynthesiaGenerator
from .runway_generator import RunwayGenerator
from .stable_video_generator import StableVideoGenerator

class VideoManager:
    """Manages multiple video generators with automatic selection"""
    
    def __init__(self):
        self.generators = [
            SynthesiaGenerator(),
            RunwayGenerator(),
            StableVideoGenerator()
        ]
        self.active_generator = self._get_active_generator()
    
    def _get_active_generator(self):
        """Get the first available video generator"""
        for generator in self.generators:
            if generator.is_available():
                return generator
        return None
    
    def is_available(self) -> bool:
        """Check if any video generator is available"""
        return self.active_generator is not None
    
    def generate_video_quiz(self, topic: str, course_id: int, duration: int = 300, difficulty: str = "medium") -> Dict[str, Any]:
        """Generate video quiz and prepare for Canvas upload"""
        if not self.active_generator:
            return {
                "success": False,
                "error": "No video generator configured. Please set API keys for Synthesia, Runway ML, or Stability AI.",
                "available_generators": [g.name for g in self.generators]
            }
        
        try:
            # Generate video quiz
            result = self.active_generator.generate_video_quiz(topic, duration, difficulty)
            
            if result["success"]:
                # Prepare Canvas integration data
                result["canvas_data"] = {
                    "course_id": course_id,
                    "assignment_name": f"{topic} Video Quiz",
                    "assignment_type": "online_quiz",
                    "points_possible": len(result.get("quiz_questions", [])) * 10,
                    "description": f"Interactive video quiz about {topic}",
                    "video_url": result.get("video_url"),
                    "quiz_questions": result.get("quiz_questions", [])
                }
            
            return result
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "generator": self.active_generator.name
            }
    
    def generate_educational_video(self, topic: str, course_id: int, duration: int = 300, style: str = "lecture") -> Dict[str, Any]:
        """Generate educational video and prepare for Canvas upload"""
        if not self.active_generator:
            return {
                "success": False,
                "error": "No video generator configured. Please set API keys.",
                "available_generators": [g.name for g in self.generators]
            }
        
        try:
            # Generate educational video
            result = self.active_generator.generate_educational_video(topic, duration, style)
            
            if result["success"]:
                # Prepare Canvas integration data
                result["canvas_data"] = {
                    "course_id": course_id,
                    "module_name": f"{topic} - Educational Video",
                    "page_title": f"{topic} Video Lesson",
                    "page_body": f"""
                    <h2>{topic} Video Lesson</h2>
                    <video controls width="100%">
                        <source src="{result.get('video_url')}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                    <p>Duration: {duration//60} minutes | Style: {style}</p>
                    <p>Generated by: {result.get('generator')}</p>
                    """,
                    "video_url": result.get("video_url")
                }
            
            return result
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "generator": self.active_generator.name
            }
    
    def get_available_generators(self) -> List[Dict[str, Any]]:
        """Get list of available video generators"""
        return [
            {
                "name": gen.name,
                "available": gen.is_available(),
                "max_duration": gen.get_max_duration(),
                "formats": gen.get_supported_formats()
            }
            for gen in self.generators
        ]
    
    def get_status(self) -> Dict[str, Any]:
        """Get status of video generation system"""
        return {
            "available_generators": self.get_available_generators(),
            "active_generator": self.active_generator.name if self.active_generator else None,
            "total_generators": len(self.generators)
        }